### ISSUE TITLE
Working with relations (translation bundle)

### ISSUE THREAD

**Issue by ruscon** [simplethings/EntityAudit#105]
Hi, i using translation bundle https://github.com/a2lix/TranslationFormBundle
And Audit bundle don't create any schema for relation tables automatically.

Its work only if i prescribed in the manual as in example

``` yaml
    simple_things_entity_audit:
        audited_entities:
            - MyBundle\Entity\MyEntity
            - MyBundle\Entity\MyEntity2
```

Can you check this, please.

And how to show in SonataAdmin history page with translation field ?
May be have some examples ?
