### ISSUE TITLE
I want to bypass postPersist() from adding entry in the audit entities

### ISSUE THREAD

**Issue by ravindrakhokharia** [simplethings/EntityAudit#188]
Hi, 

I wanted to know if there is a possibility to bypass the postPersist() method for auditing any entity, for may be specific tables only ? 

like - LogRevisionsListener 

Any help will be appreciated. 

Thanks!

**Comment by tolry** [comment]
Hi @ravindrakhokharia,

could you elaborate a bit more on what you are trying to achieve? It is already possible to audit only certain tables/entity classes, see README

##### app/config/config.yml
```yml
simple_things_entity_audit:
    audited_entities:
        - MyBundle\Entity\MyEntity
        - MyBundle\Entity\MyEntity2
```

Or do you need to exclude certain entries of one table from being audited?
